create table "users"
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"    varchar(50),
    "login"   varchar(50),
    "password"    varchar(50)
);

CREATE TABLE "clients" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL
);

CREATE TABLE "addresses" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "address" VARCHAR(255) NOT NULL,
    "client_id" BIGINT,
    FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE
);

CREATE TABLE "phones" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "number" VARCHAR(255) NOT NULL,
    "client_id" BIGINT,
    FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE
);
